language: php

services:
  - mysql

env:
  - SCOUT_DRIVER=elastic SCOUT_ELASTIC_INDEXER=bulk SCOUT_ELASTIC_HOST=localhost:9200 DB_DATABASE=my_database DB_USERNAME=travis DB_PASSWORD=""

php:
  - 7.3

cache:
  directories:
    - "$HOME/.composer/cache/files"

before_script:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.2.deb && sudo dpkg -i --force-confnew elasticsearch-6.6.2.deb && sudo service elasticsearch restart
  - mysql -e "create database $DB_DATABASE;"
  - (cd database/seeds/test_db && mysql < employees.sql)
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --no-suggest --prefer-source
  - curl -X GET "localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s"
  - php artisan vendor:publish --provider="Laravel\Scout\ScoutServiceProvider"
  - php artisan vendor:publish --provider="ScoutElastic\ScoutElasticServiceProvider"
  - php artisan make:index-configurator EmployeeIndexConfigurator
  - php artisan elastic:create-index "App\EmployeeIndexConfigurator"
script:
  - time php artisan debug
